[languages.cpp]
compile = "cmd /c \"{CXX} {CXXFLAGS} -o {tempdir}\\a.exe {path} && echo @echo off > {tempdir}\\a.out.bat && echo {tempdir}\\a.exe >> {tempdir}\\a.out.bat\""
execute = "cmd /c {tempdir}\\a.out.bat"
bundle = "false"
list_dependencies = "cmd /c type {path} | findstr /R \"^#include \\\".*\\\"\""